work_dir: ./work_dir/fall_detection/joint

# feeder
feeder: feeders.feeder_fall.Feeder
train_feeder_args:
  data_path: ../processed_data/X_train.npy
  label_path: ../processed_data/y_train.npy
  split: train
  debug: False
  random_choose: False
  random_shift: True
  random_move: True
  window_size: 30
  normalization: False
  random_rot: True
  vel: False
  bone: False

test_feeder_args:
  data_path: ../processed_data/X_test.npy
  label_path: ../processed_data/y_test.npy
  split: test
  window_size: 30
  vel: False
  bone: False
  debug: False

# model
model: model.ctrgcn.Model
model_args:
  num_class: 2
  num_point: 17
  num_person: 1
  graph: graph.coco.Graph
  window_size: 30
  graph_args:
    labeling_mode: 'spatial'
  joint_label: [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]

# optim
weight_decay: 0.0004
base_lr: 0.01
lr_decay_rate: 0.1
step: [60, 80]
warm_up_epoch: 5

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 100
nesterov: True
